#
# Copyright 2023 Maestro Cloud Control LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
#




#not used for local files
m3.autoconfiguration.bucket.name=none

m3.chef.version=15
m3.chef.env=prod
m3.chef.prefix=m3
m3.chef.conf.url=http:/localhost:8082/chef/conf/
m3.chef.state.url=http:/localhost:8082/chef/state/
m3.chef.cert.url=http:/localhost:8082/chef/cert/
m3.chef.node.name=agent
m3.chef.ini.storage.url=http:/localhost:8082/chef/init/
m3.chef.api.host=http:/localhost:8082/chef/api/
m3.chef.enabled=true
m3.userscripts.enabled=false
